version: '3'
services:
  mongo:
    image: "mongo:3"
    restart: always
    volumes:
      - ./:/graylog/data/db
  elasticsearch:
    image: "elasticsearch:5.6"
    volumes:
      -  ./:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    restart: always
  kibana:
    image: "kibana:5.6"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
  graylog:
    image: "graylog/graylog:2.4"
    volumes:
      - ./:/graylog/usr/share/graylog/data/journal
      - ./:/graylog/usr/share/graylog/data/config
    environment:
      GRAYLOG_PASSWORD_SECRET: 99e254cd51a49fadada94dc8e6ce9af8ab30b05dff67b159b2f232eb432eb2f3
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_REST_LISTEN_URI: http://0.0.0.0:9000/api
      GRAYLOG_WEB_LISTEN_URI: http://0.0.0.0:9000/
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514/udp"
      - "27017:27017"
      - "514:514"
      - "514:514/udp"
    restart: always
